version: '3.8'
services:
  jobs:
    build:
      context: .
      dockerfile: ./apps/jobs/Dockerfile
      target: development
    command: pnpm run start:dev jobs
    env_file:
      - ./apps/jobs/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
    ports:
      - '27017:27017'
